In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings("ignore")

In [3]:
a=pd.read_csv('advertising.csv')

In [4]:
a

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [5]:
a.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [6]:
a.tail()

TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [7]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [8]:
a.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [9]:
a.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [11]:
a.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [13]:
a.shape

(200, 4)

In [14]:
x=a.iloc[:,:-1]
y=a.iloc[:,-1]

In [15]:
x

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [16]:
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [19]:
lr=LinearRegression()

In [20]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [22]:
ypred=lr.predict(xtest)

In [30]:
lr.score(xtest,ytest)

0.9091484341849799

In [31]:
lr.coef_

array([0.05358869, 0.10270677, 0.00793167])

In [23]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [25]:
mae=mean_absolute_error(ytest,ypred)
mae

1.1594875061090586

In [28]:
mse=mean_squared_error(ytest,ypred)
mse

2.541624036229149

In [29]:
r2=r2_score(ytest,ypred)
r2

0.9091484341849799

In [32]:
from sklearn.preprocessing import PolynomialFeatures

In [33]:
a=PolynomialFeatures(2)

In [34]:
xtraintrans=a.fit_transform(xtrain)
xtesttrans=a.fit_transform(xtest)

In [36]:
xtraintrans


array([[1.00000e+00, 2.84300e+02, 1.06000e+01, ..., 1.12360e+02,
        6.78400e+01, 4.09600e+01],
       [1.00000e+00, 1.84900e+02, 2.10000e+01, ..., 4.41000e+02,
        4.62000e+02, 4.84000e+02],
       [1.00000e+00, 1.12900e+02, 1.74000e+01, ..., 3.02760e+02,
        6.71640e+02, 1.48996e+03],
       ...,
       [1.00000e+00, 2.17700e+02, 3.35000e+01, ..., 1.12225e+03,
        1.97650e+03, 3.48100e+03],
       [1.00000e+00, 1.65600e+02, 1.00000e+01, ..., 1.00000e+02,
        1.76000e+02, 3.09760e+02],
       [1.00000e+00, 2.80200e+02, 1.01000e+01, ..., 1.02010e+02,
        2.16140e+02, 4.57960e+02]])

In [37]:
xtesttrans

array([[1.000000e+00, 1.633000e+02, 3.160000e+01, 5.290000e+01,
        2.666689e+04, 5.160280e+03, 8.638570e+03, 9.985600e+02,
        1.671640e+03, 2.798410e+03],
       [1.000000e+00, 1.954000e+02, 4.770000e+01, 5.290000e+01,
        3.818116e+04, 9.320580e+03, 1.033666e+04, 2.275290e+03,
        2.523330e+03, 2.798410e+03],
       [1.000000e+00, 2.929000e+02, 2.830000e+01, 4.320000e+01,
        8.579041e+04, 8.289070e+03, 1.265328e+04, 8.008900e+02,
        1.222560e+03, 1.866240e+03],
       [1.000000e+00, 1.170000e+01, 3.690000e+01, 4.520000e+01,
        1.368900e+02, 4.317300e+02, 5.288400e+02, 1.361610e+03,
        1.667880e+03, 2.043040e+03],
       [1.000000e+00, 2.203000e+02, 4.900000e+01, 3.200000e+00,
        4.853209e+04, 1.079470e+04, 7.049600e+02, 2.401000e+03,
        1.568000e+02, 1.024000e+01],
       [1.000000e+00, 7.510000e+01, 3.500000e+01, 5.270000e+01,
        5.640010e+03, 2.628500e+03, 3.957770e+03, 1.225000e+03,
        1.844500e+03, 2.777290e+03],
       [1.